### ISSUE TITLE
Build failure on epi-core

### ISSUE THREAD

**Issue by yihsuan1102** [ptidejteam/ptidej-Ptidej#2]
After commenting out the demima-ui-cpp, there is a compilation failure during installing. 
The following is the error messages.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project epi-core: Compilation failure: Compilation failure:
[ERROR] /C:/project/ptidej-Ptidej/EPI/src/main/java/epi/solver/problem/Problem.java:[20,33] package ptidej.solver.fingerprint does not exist
[ERROR] /C:/project/ptidej-Ptidej/EPI/src/main/java/epi/solver/problem/Problem.java:[27,19] cannot find symbol
[ERROR]   symbol:   class ReducedDomainBuilder
[ERROR]   location: class epi.solver.problem.Problem
[ERROR] /C:/project/ptidej-Ptidej/EPI/src/main/java/epi/solver/problem/AbstractFactory.java:[14,33] package ptidej.solver.fingerprint does not exist
[ERROR] /C:/project/ptidej-Ptidej/EPI/src/main/java/epi/solver/problem/Composite.java:[14,33] package ptidej.solver.fingerprint does not exist
[ERROR] /C:/project/ptidej-Ptidej/EPI/src/main/java/epi/solver/problem/Problem.java:[30,32] cannot find symbol
[ERROR]   symbol:   class ReducedDomainBuilder
[ERROR]   location: class epi.solver.problem.Problem
[ERROR] /C:/project/ptidej-Ptidej/EPI/src/main/java/epi/solver/problem/AbstractFactory.java:[27,55] cannot find symbol
[ERROR]   symbol:   variable Rule
[ERROR]   location: class epi.solver.problem.AbstractFactory
[ERROR] /C:/project/ptidej-Ptidej/EPI/src/main/java/epi/solver/problem/AbstractFactory.java:[31,55] cannot find symbol
[ERROR]   symbol:   variable Rule
[ERROR]   location: class epi.solver.problem.AbstractFactory
[ERROR] /C:/project/ptidej-Ptidej/EPI/src/main/java/epi/solver/problem/AbstractFactory.java:[34,55] cannot find symbol
[ERROR]   symbol:   variable Rule
[ERROR]   location: class epi.solver.problem.AbstractFactory
[ERROR] /C:/project/ptidej-Ptidej/EPI/src/main/java/epi/solver/problem/Composite.java:[26,47] cannot find symbol
[ERROR]   symbol:   variable Rule
```
The import of ptidej.solver.fingerprint in these java files cannot resolve, and ptidej.solver.fingerprint file doesn't exist in EPI folder.
How can I fix this problem?

**Comment by yann-gael** [comment]
The class `ptidej.solver.fingerprint.ReducedDomainBuilder` actually exists in `/DeMIMA Solver Fingerprints/src/main/java/ptidej/solver/fingerprint/ReducedDomainBuilder.java` (see https://github.com/ptidejteam/ptidej-Ptidej/tree/master/DeMIMA%20Solver%20Fingerprints/src/main/java/ptidej/solver/fingerprint). Could you check in your workspace if you have this project (`DeMIMA Solver Fingerprints`) and this file (`src/main/java/ptidej/solver/fingerprint/ReducedDomainBuilder.java`)?

**Comment by yihsuan1102** [comment]
> The class `ptidej.solver.fingerprint.ReducedDomainBuilder` actually exists in `/DeMIMA Solver Fingerprints/src/main/java/ptidej/solver/fingerprint/ReducedDomainBuilder.java` (see https://github.com/ptidejteam/ptidej-Ptidej/tree/master/DeMIMA%20Solver%20Fingerprints/src/main/java/ptidej/solver/fingerprint). Could you check in your workspace if you have this project (`DeMIMA Solver Fingerprints`) and this file (`src/main/java/ptidej/solver/fingerprint/ReducedDomainBuilder.java`)?

Project (DeMIMA Solver Fingerprints) and file (src/main/java/ptidej/solver/fingerprint/ReducedDomainBuilder.java) are exist in my wokplace.

> The project `DeMIMA Solver Fingerprints` compiles into the module `demima-solver-fingerprints` (in `net.ptidej.demima`), which is referenced into `/EPI/pom.xml`. Could you also check that the dependency is indeed present in your `/EPI/pom.xml`? (As in `https://github.com/ptidejteam/ptidej-Ptidej/blob/master/EPI/pom.xml`.)

 `/EPI/pom.xml` didn't exist dependency on module `demima-solver-fingerprints` . So, I add 
```
<dependencies>
                 <dependency>...</dependency>
                 <dependency>
			<groupId>net.ptidej.demima</groupId>
			<artifactId>demima-solver-fingerprints</artifactId>
			<version>1.0.0</version>
		</dependency>
</dependencies>
```
into  `/EPI/pom.xml`, and this issue is fixed.

Another issue is the dependency demima-solver-metrics in `/EPI/pom.xml` was commented on by me. After I restore my `/EPI/pom.xml`  as in [https://github.com/ptidejteam/ptidej-Ptidej/blob/master/EPI/pom.xml]. Another build failure on project EPI occur. The following is the error messages.

```
[WARNING] The POM for net.ptidej.demima:demima-solver-metrics:jar:1.0.0 is missing, no dependency information available
[ERROR] Failed to execute goal on project epi-core: Could not resolve dependencies for project net.ptidej.epi:epi-core:jar:1.0.0: The following artifacts could not be resolved: net.ptidej.demima:demima-solver-metrics:jar:1.0.0 (absent): 
net.ptidej.demima:demima-solver-metrics:jar:1.0.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. 
This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```
There is no demima-solver-metrics related module in the whole project.

**Comment by yann-gael** [comment]
That's strange: why would the dependency declaration be missing from your `pom.xml` but be in the repo.?

Regarding `demima-solver-metrics`, that's indeed a bug: this dependency refers to the old project artifactID. Please replace it with:

```
		<dependency>
			<groupId>net.ptidej.demima</groupId>
			<artifactId>demima-solver-fingerprints</artifactId>
			<version>1.0.0</version>
		</dependency>
```

and let me know if that compiles now...

**Comment by yihsuan1102** [comment]
> That's strange: why would the dependency declaration be missing from your `pom.xml` but be in the repo.?
I commented on the `demima-solver-metrics` module in ` /EPI/pom.xml` when a build failure occurred before. I forgot to restore comments and the comments that shouldn't be there were found until I reopened /EPI/pom.xml...

The fix works, Thank you.

**Comment by yann-gael** [comment]
https://github.com/ptidejteam/ptidej-Ptidej/commit/243bd7fe77826f2d1a144fb899573d04d4117c41
